POST http://localhost:4000/api/auth/revoke-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZGJjOGNjM2QzZGZmNjllNmIyMzE1MSIsImVtYWlsIjoidmljdG9yZ21wQGdtYWlsLmNvbSIsImlhdCI6MTYyNTA2MzYxMywiZXhwIjoxNjI1MDY0NTEzfQ.jLQJiDdHUkR7ro_PmKRcMkzqN4vZxtWq1yGF30UREhc

{
  "token": "854dbdeea32c49cca26ebd2f66c843cd9886bac13f7a99229e3f83823dd26a0ecc6d0b9187b8300b"
}