POST http://localhost:4000/api/auth/revoke-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZGI3N2FjZmZiZmVmYmQ1ODMwZjNlMyIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTYyNDk5Nzc1NSwiZXhwIjoxNjI0OTk4NjU1fQ.t04CIYeCsqLPHn8sILBg_BpoGuYcPe-aNeCopvCtu7M

{
  "token": "0183f4ddf7c7655950fb92ba96dec40388ce42dd719dc73a5b7b08a743034bd67312ec751b432c99"
}